version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dart-dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      example-dependencies:
        patterns:
          - "*"
